query all {
    webApiServices {
        {{WebApiService}}
    }
    soapServices {
        {{SoapService}}
    }
    internalWebApiServices {
        {{InternalWebApiService}}
    }
    internalSoapServices {
        {{InternalSoapService}}
    }
    encassConfigs {
        {{EncassConfig}}
    }
    globalPolicies {
        {{GlobalPolicy}}
    }
    backgroundTaskPolicies {
        {{BackgroundTaskPolicy}}
    }
    policyFragments {
        {{PolicyFragment}}
    }
    
    activeConnectors {
        {{ActiveConnector:-hardwiredService}}
    }
    cassandraConnections {
        {{CassandraConnection}}
    }
    clusterProperties {
        {{ClusterProperty}}
    }
    dtds {
        {{Dtd}}
    }
    emailListeners {
        {{EmailListener:-hardwiredService}}
    }
    fips {
        {{Fip}}
    }
    fipGroups {
        {{FipGroup}}
    }
    fipUsers {
        {{FipUser}}
    }
    internalDtds {
        {{Dtd}}
    }
    internalGroups {
        {{InternalGroup}}
    }
    internalSchemas {
        {{Schema}}
    }
    internalUsers {
        {{InternalUser}}
    }
    jdbcConnections {
        {{JdbcConnection}}
    }
    jmsDestinations {
        {{JmsDestination}}
    }
    keys {
        {{Key}}
    }
    ldaps {
        {{Ldap}}
    }
    listenPorts {
        {{ListenPort:-hardwiredService}}
    }
    scheduledTasks {
        {{ScheduledTask}}
    }
    schemas {
        {{Schema}}
    }
    secrets {
        {{Secret}}
    }
    serverModuleFiles {
        {{ServerModuleFile:-filePartName}}
    }
    smConfigs {
        {{SMConfig}}
    }
    trustedCerts {
        {{Certificate}}
    }
}
