query folderSummary ($folderPath: String!) {
    
    webApiServicesByFolderPath (folderPath: $folderPath) {
        {{WebApiService:summary}}
    }
    soapServicesByFolderPath (folderPath: $folderPath) {
        {{SoapService:summary}}
    }
	internalWebApiServicesByFolderPath (folderPath: $folderPath) {
        {{InternalWebApiService:summary}}
    }
    internalSoapServicesByFolderPath (folderPath: $folderPath) {
        {{InternalSoapService:summary}}
    }
	encassConfigsByFolderPath (folderPath: $folderPath) {
        {{EncassConfig:summary}}
    }
	globalPoliciesByFolderPath (folderPath: $folderPath) {
        {{GlobalPolicy:summary}}
    }
    backgroundTaskPoliciesByFolderPath (folderPath: $folderPath) {
        {{BackgroundTaskPolicy:summary}}
    }
    policyFragmentsByFolderPath (folderPath: $folderPath) {
        {{PolicyFragment:summary}}
    }
	
}
