query all {
    services {
        {{L7Service:-policyRevision,policyRevisions}}
    }
    encassConfigs {
        {{EncassConfig}}
    }
    policies {
        {{L7Policy:-policyRevision,policyRevisions}}
    }
    activeConnectors {
        {{ActiveConnector:-hardwiredService}}
    }
    cassandraConnections {
        {{CassandraConnection}}
    }
    clusterProperties {
        {{ClusterProperty}}
    }
    dtds {
        {{Dtd}}
    }
    emailListeners {
        {{EmailListener:-hardwiredService}}
    }
    federatedIdps {
        {{FederatedIdp}}
    }
    federatedGroups {
        {{FederatedGroup:-members}}
    }
    federatedUsers {
        {{FederatedUser:-memberOf}}
    }
    internalDtds {
        {{Dtd}}
    }
    internalGroups {
        {{InternalGroup}}
    }
    internalSchemas {
        {{Schema}}
    }
    internalUsers {
        {{InternalUser}}
    }
    jdbcConnections {
        {{JdbcConnection}}
    }
    jmsDestinations {
        {{JmsDestination}}
    }
    keys {
        {{Key}}
    }
    ldapIdps {
        {{LdapIdp}}
    }
    listenPorts {
        {{ListenPort:-hardwiredService}}
    }
    scheduledTasks {
        {{ScheduledTask}}
    }
    schemas {
        {{Schema}}
    }
    secrets {
        {{Secret}}
    }
    serverModuleFiles {
        {{ServerModuleFile:-filePartName}}
    }
    smConfigs {
        {{SMConfig}}
    }
    revocationCheckPolicies {
        {{RevocationCheckPolicy}}
    }
    trustedCerts {
        {{Certificate}}
    }
    logSinks {
        {{LogSink}}
    }
    httpConfigurations {
        {{HttpConfiguration}}
    }
    customKeyValues {
        {{CustomKeyValue}}
    }
    simpleLdapIdps {
        {{SimpleLdapIdp}}
    }
    policyBackedIdps {
        {{PolicyBackedIdp}}
    }
    internalIdps {
        {{InternalIdp}}
    }
}
