query encassByName ($name: String!, $policyName: String!, $includeDirectDependencies: Boolean = false, $includeAllDependencies: Boolean = false) {
    encassConfigByName (name: $name) {
        {{EncassConfig}}
    }
    policyFragmentByName(name: $policyName) {
        {{PolicyFragment:-policy}}
        policy {
            xml
            directDependencies @include (if: $includeDirectDependencies) {
                {{PolicyDependency}}
            }
            allDependencies @include (if: $includeAllDependencies) {
                {{PolicyDependency}}
            }
        }
    }
}
