query encassByName ($name: String!, $policyName: String!, $includeAllDependencies: Boolean = false) {
    encassConfigByName (name: $name) {
        {{EncassConfig}}
    }
    policyByName(name: $policyName) {
        {{L7Policy:-policy}}
        policy {
            xml
            allDependencies @include (if: $includeAllDependencies) {
                {{PolicyDependency:-policyFragments,-ldaps,-fips,-fipUsers,-fipGroups}}
            }
        }
    }
}
