query folderContents ($folderPath: String!, $includeAllDependencies: Boolean = false, $includeDirectDependencies: Boolean = false) {
    
    webApiServicesByFolderPath (folderPath: $folderPath) {
        {{WebApiService:-policy}}
        policy {
            xml
            allDependencies @include (if: $includeAllDependencies) {
                {{PolicyDependency}}
            }
			directDependencies @include (if: $includeDirectDependencies) {
                {{PolicyDependency}}
            }
        }
    }
	
    soapServicesByFolderPath (folderPath: $folderPath) {
        {{SoapService:-policy}}
        policy {
            xml
            allDependencies @include (if: $includeAllDependencies) {
                {{PolicyDependency}}
            }
			directDependencies @include (if: $includeDirectDependencies) {
                {{PolicyDependency}}
            }
        }
    }
	
	internalWebApiServicesByFolderPath (folderPath: $folderPath) {
        {{WebApiService:-policy}}
        policy {
            xml
            allDependencies @include (if: $includeAllDependencies) {
                {{PolicyDependency}}
            }
			directDependencies @include (if: $includeDirectDependencies) {
                {{PolicyDependency}}
            }
        }
    }
	
    internalSoapServicesByFolderPath (folderPath: $folderPath) {
        {{SoapService:-policy}}
        policy {
            xml
            allDependencies @include (if: $includeAllDependencies) {
                {{PolicyDependency}}
            }
			directDependencies @include (if: $includeDirectDependencies) {
                {{PolicyDependency}}
            }
        }
    }
	
	encassConfigsByFolderPath (folderPath: $folderPath) {
        {{EncassConfig}}
    }
	
	globalPoliciesByFolderPath (folderPath: $folderPath) {
        {{GlobalPolicy:-policy}}
        policy {
            xml
            allDependencies @include (if: $includeAllDependencies) {
                {{PolicyDependency}}
            }
			directDependencies @include (if: $includeDirectDependencies) {
                {{PolicyDependency}}
            }
        }
    }

	backgroundTaskPoliciesByFolderPath (folderPath: $folderPath) {
        {{BackgroundTaskPolicy:-policy}}
        policy {
            xml
            allDependencies @include (if: $includeAllDependencies) {
                {{PolicyDependency}}
            }
			directDependencies @include (if: $includeDirectDependencies) {
                {{PolicyDependency}}
            }
        }
    }
	
	policyFragmentsByFolderPath (folderPath: $folderPath) {
        {{PolicyFragment:-policy}}
        policy {
            xml
            allDependencies @include (if: $includeAllDependencies) {
                {{PolicyDependency}}
            }
			directDependencies @include (if: $includeDirectDependencies) {
                {{PolicyDependency}}
            }
        }
    }
	
}
