query folderSummary ($folderPath: String!) {
    
    servicesByFolderPath (folderPath: $folderPath) {
        {{L7Service:summary}}
    }

    encassConfigsByFolderPath (folderPath: $folderPath) {
        {{EncassConfig:summary}}
    }

    policiesByFolderPath (folderPath: $folderPath) {
        {{L7Policy:summary}}
    }
	
}
