query folderContents ($folderPath: String!, $includeAllDependencies: Boolean = false, $includePolicyRevision: Boolean = false, $includePolicyRevisions: Boolean = false) {
    servicesByFolderPath (folderPath: $folderPath) {
        {{L7Service:-policy}}
        policy {
            xml
            allDependencies @include (if: $includeAllDependencies) {
                {{PolicyDependency:-policyFragments,-ldaps,-fips,-fipUsers,-fipGroups}}
            }
        }
        policyRevision @include (if: $includePolicyRevision) {
            {{PolicyRevision}}
        }
        policyRevisions @include (if: $includePolicyRevisions) {
            {{PolicyRevision}}
        }
    }

	encassConfigsByFolderPath (folderPath: $folderPath) {
        {{EncassConfig}}
    }

	policiesByFolderPath (folderPath: $folderPath) {
        {{L7Policy:-policy}}
        policy {
            xml
            allDependencies @include (if: $includeAllDependencies) {
                {{PolicyDependency:-policyFragments,-ldaps,-fips,-fipUsers,-fipGroups}}
            }
        }
        policyRevision @include (if: $includePolicyRevision) {
            {{PolicyRevision}}
        }
        policyRevisions @include (if: $includePolicyRevisions) {
            {{PolicyRevision}}
        }
    }
}
