query globalPoliciesAndTasks {
    globalPolicies {
        {{GlobalPolicy}}
    }
    backgroundTaskPolicies {
        {{BackgroundTaskPolicy}}
    }
    scheduledTasks {
        {{ScheduledTask}}
    }
}

