query secretByName($name: String!) {
    secretByName(name : $name) {
        goid
        name
        checksum

        description
        secret
        secretType
        variableReferencable
    }
}