query serviceByResolutionPath ($resolutionPath: String!, $includeAllDependencies: Boolean = false, $includePolicyRevision: Boolean = false, $includePolicyRevisions: Boolean = false) {
    serviceByResolutionPath (resolutionPath: $resolutionPath) {
        {{L7Service:-policy}}
         policy {
            xml
            allDependencies @include (if: $includeAllDependencies) {
                {{PolicyDependency:-policyFragments,-ldaps,-fips,-fipUsers,-fipGroups}}
            }
        }
        policyRevision @include (if: $includePolicyRevision) {
            {{PolicyRevision}}
        }
        policyRevisions @include (if: $includePolicyRevisions) {
            {{PolicyRevision}}
        }
    }
}
