query soapServiceByResolver ($resolver: SoapServiceResolverInput!, $includeDirectDependencies: Boolean = false, $includeAllDependencies: Boolean = false) {
    soapServiceByResolver (resolver: $resolver) {
        {{SoapService:-policy}}
        policy {
            xml
            directDependencies @include (if: $includeDirectDependencies) {
                {{PolicyDependency}}
            }
            allDependencies @include (if: $includeAllDependencies) {
                {{PolicyDependency}}
            }
        }
    }
}
