query summary {
    services {
        {{L7Service:summary}}
    }
    encassConfigs {
        {{EncassConfig:summary}}
    }
    policies {
        {{L7Policy:summary}}
    }
    activeConnectors {
        {{ActiveConnector:summary}}
    }
    cassandraConnections {
        {{CassandraConnection:summary}}
    }
    clusterProperties {
        {{ClusterProperty:summary}}
    }
    dtds {
        {{Dtd:summary}}
    }
    emailListeners {
        {{EmailListener:summary}}
    }
    federatedIdps {
        {{FederatedIdp:summary}}
    }
    federatedGroups {
        {{FederatedGroup:summary}}
    }
    federatedUsers {
        {{FederatedUser:summary}}
    }
    internalDtds {
        {{Dtd:summary}}
    }
    internalGroups {
        {{InternalGroup:summary}}
    }
    internalSchemas {
        {{Schema:summary}}
    }
    internalUsers {
        {{InternalUser:summary}}
    }
    jdbcConnections {
        {{JdbcConnection:summary}}
    }
    jmsDestinations {
        {{JmsDestination:summary}}
    }
    keys {
        {{Key:summary}}
    }
    ldapIdps {
        {{LdapIdp:summary}}
    }
    listenPorts {
        {{ListenPort:summary}}
    }
    scheduledTasks {
        {{ScheduledTask:summary}}
    }
    schemas {
        {{Schema:summary}}
    }
    secrets {
        {{Secret:summary}}
    }
    serverModuleFiles {
        {{ServerModuleFile:summary}}
    }
    smConfigs {
        {{SMConfig:summary}}
    }
    revocationCheckPolicies {
        {{RevocationCheckPolicy:summary}}
    }
    trustedCerts {
        {{Certificate:summary}}
    }
    logSinks {
        {{LogSink:summary}}
    }
    httpConfigurations {
        {{HttpConfiguration:summary}}
    }
    customKeyValues {
        {{CustomKeyValue:summary}}
    }
    simpleLdapIdps {
        {{SimpleLdapIdp:summary}}
    }
    policyBackedIdps {
        {{PolicyBackedIdp:summary}}
    }
    internalIdps {
        {{InternalIdp:summary}}
    }
}
