mutation applyBundle (
    $administrativeUserAccountProperties: [AdministrativeUserAccountPropertyInput!]!=[],
    $passwordPolicies: [PasswordPolicyInput!]!=[],
    $serviceResolutionConfigs:[ServiceResolutionConfigInput!]!=[]) {
        setAdministrativeUserAccountProperties(input: $administrativeUserAccountProperties) {detailedStatus {status description source{name value} target{name value}}}
        setPasswordPolicies(input: $passwordPolicies) {detailedStatus {status description source{name value} target{name value}}}
        setServiceResolutionConfigs(input: $serviceResolutionConfigs) {detailedStatus {status description source{name value} target{name value}}}
}
