query systemAdministration {
    administrativeUserAccountProperties {
        {{AdministrativeUserAccountProperty}}
    }
    passwordPolicies {
        {{PasswordPolicy}}
    }
    serviceResolutionConfigs {
        {{ServiceResolutionConfig}}
    }
}
