query apis {
    webApiServicesByFolderPath (folderPath: "/myApis") {
        goid
        name
        resolutionPath
        checksum
        folderPath
        policy {
            xml
        }
        enabled
        methodsAllowed
        tracingEnabled
        wssProcessingEnabled
    }
}