query apis {
    webApiServicesByFolderPath (folderPath: "/myApis") {
        name
        checksum
        resolutionPath
        folderPath
        policy {
            xml
        }
        enabled
        methodsAllowed
    }
}