query myFramework {
    globalPoliciesByFolderPath (folderPath: "/bootstrapableFramework") {
        {{GlobalPolicy:-policy}}
        policy {
            xml
            allDependencies {
                {{PolicyDependency:-policyFragments,encassConfigs}}
            }
        }
    }
    backgroundTaskPoliciesByFolderPath (folderPath: "/bootstrapableFramework") {
        {{BackgroundTaskPolicy:-policy}}
        policy {
            xml
            allDependencies {
                {{PolicyDependency:-policyFragments,encassConfigs}}
            }
        }
    }
    policyFragmentsByFolderPath (folderPath: "/bootstrapableFramework") {
        {{PolicyFragment:-policy}}
        policy {
            xml
            allDependencies {
                {{PolicyDependency:-policyFragments,encassConfigs}}
            }
        }
    }
    scheduledTasks {
        {{ScheduledTask}}
    }
}