query plans {
    clusterPropertyByNameA: clusterPropertyByName (name: "plan_a_members") {
        goid
        name
        value
        hiddenProperty
        description
    }
    clusterPropertyByNameB:  clusterPropertyByName (name: "plan_b_members") {
        goid
        name
        value
        hiddenProperty
        description
    }
    clusterPropertyByNameC:  clusterPropertyByName (name: "plan_c_members") {
        goid
        name
        value
        hiddenProperty
        description
    }
}